import { PlatformPageTemplate } from "@/components/landing/PlatformPageTemplate";

export const metadata = {
  title: "CRM | Crawlia",
  description: "Track every prospect from cold lead to closed deal with our built-in CRM.",
};

export default function CRMPage() {
  return (
    <PlatformPageTemplate
      badge="CRM"
      title="Track every prospect from cold lead to closed deal."
      subtitle="A built-in CRM that tracks where the money is at. Pipeline stages, win rate, deal values, and a unified team inbox."
      bulletPoints={[
        "Customizable pipeline stages",
        "Automatic interest tagging",
        "Unified inbox for your whole team",
        "Advanced revenue tracking"
      ]}
      heroImage="/images/mockups/dashboard_leads_page_1785438100855.png"
      topFeatures={[
        {
          title: "Pipeline stages",
          description: "Customize the board to match your exact sales flow. Drag and drop leads as they progress."
        },
        {
          title: "Unified team inbox",
          description: "Manage all conversations from all sender mailboxes in one unified, collaborative inbox."
        },
        {
          title: "Custom filters",
          description: "Easily save and load filters to instantly see the leads that matter most to your revenue."
        }
      ]}
      midSectionTitle="A real CRM, not a stripped-down extension."
      midSectionSubtitle="Find out how we replace expensive standalone CRM tools for most teams doing cold outreach at scale."
      detailedFeatures={[
        { title: "Custom stages", description: "Rename, reorder, and add stages to your pipeline to perfectly match your agency's sales process." },
        { title: "Smart classification", description: "Our AI reads replies in real-time and automatically tags them as Interested, OOO, or Bounce so you save hours." },
        { title: "Notes & reminders", description: "Add crucial context to any lead by dropping an internal note and setting a follow-up reminder for your team." },
        { title: "Value tracking", description: "Assign a deal value to leads to instantly see how much potential revenue is sitting in your pipeline." },
        { title: "Deal rotting", description: "Visually see which leads are getting cold because they haven't been contacted in too many days." },
        { title: "Export to CSV", description: "One-click export all your pipeline data out to your accounting or reporting tools whenever you need it." }
      ]}
      howItWorksSteps={[
        { title: "Setup your pipeline", description: "Map out your sales stages from cold lead all the way to closed won in just a few clicks." },
        { title: "Connect your mailboxes", description: "Securely link your Google Workspace or Microsoft Outlook accounts via OAuth." },
        { title: "Launch your campaign", description: "Start sending personalized emails generated by our AI directly to your prospect list." },
        { title: "AI tags the replies", description: "As replies come in, the AI reads the context and sorts them automatically." },
        { title: "Review interested leads", description: "Your sales team logs in and focuses 100% of their time only on the hot, interested leads." },
        { title: "Close the deals", description: "Drag the leads across the finish line to Closed Won and celebrate the new revenue." }
      ]}
    />
  );
}
